annotations:
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/display-name: Istio
  catalog.cattle.io/kube-version: '>= 1.27.0-0 < 1.32.0-0'
  catalog.cattle.io/namespace: istio-system
  catalog.cattle.io/os: linux
  catalog.cattle.io/permits-os: linux,windows
  catalog.cattle.io/rancher-version: '>= 2.10.0-0 < 2.11.0-0'
  catalog.cattle.io/release-name: rancher-istio
  catalog.cattle.io/requests-cpu: 710m
  catalog.cattle.io/requests-memory: 2314Mi
  catalog.cattle.io/type: cluster-tool
  catalog.cattle.io/ui-component: istio
  catalog.cattle.io/upstream-version: 1.23.2
apiVersion: v1
appVersion: 1.23.2
description: A basic Istio setup that installs with the istioctl. Refer to https://istio.io/latest/
  for details.
icon: https://charts.rancher.io/assets/logos/istio.svg
keywords:
- networking
- infrastructure
name: rancher-istio
version: 105.5.1+up1.24.1
