annotations:
  catalog.cattle.io/auto-install: rancher-compliance-crd=match
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/display-name: Rancher Compliance
  catalog.cattle.io/kube-version: '>= 1.31.0-0 < 1.34.0-0'
  catalog.cattle.io/namespace: rancher-compliance-system
  catalog.cattle.io/os: linux
  catalog.cattle.io/permits-os: linux,windows
  catalog.cattle.io/provides-gvr: compliance.cattle.io.clusterscans/v1
  catalog.cattle.io/rancher-version: '>= 2.12.0-0 < 2.13.0-0'
  catalog.cattle.io/release-name: rancher-compliance
  catalog.cattle.io/type: cluster-tool
  catalog.cattle.io/ui-component: rancher-compliance
apiVersion: v1
appVersion: v1.0.0-rc.1
description: The compliance-operator enables running security scans on a kubernetes
  cluster
icon: file://assets/logos/rancher-compliance.svg
keywords:
- security
name: rancher-compliance
version: 107.0.0+up1.0.0-rc.1
