annotations:
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/display-name: Prometheus Federator
  catalog.cattle.io/kube-version: '>= 1.30.0-0 < 1.33.0-0'
  catalog.cattle.io/namespace: cattle-monitoring-system
  catalog.cattle.io/os: linux,windows
  catalog.cattle.io/permits-os: linux,windows
  catalog.cattle.io/provides-gvr: helm.cattle.io.projecthelmchart/v1alpha1
  catalog.cattle.io/rancher-version: '>= 2.11.0-0 < 2.12.0-0'
  catalog.cattle.io/release-name: prometheus-federator
apiVersion: v2
appVersion: v3.1.0
description: Prometheus Federator - installs rancher-project-monitoring in project
  namespaces.
icon: file://assets/logos/prometheus-federator.svg
keywords:
- prometheus
- monitoring
- project-monitoring
maintainers:
- email: alexandre.lamarre@suse.com
  name: Alexandre
- email: dan.pock@suse.com
  name: Dan
- email: julia.suriano@suse.com
  name: Julia
name: prometheus-federator
version: 106.0.2+up3.1.0
