annotations:
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/hidden: "true"
  catalog.cattle.io/namespace: cattle-resources-system
  catalog.cattle.io/release-name: rancher-backup-crd
apiVersion: v2
appVersion: 7.0.0-alpha.3
description: Installs the CRDs for rancher-backup.
name: rancher-backup-crd
type: application
version: 106.0.0+up7.0.0-alpha.3
