annotations:
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/hidden: "true"
  catalog.cattle.io/namespace: cattle-elemental-system
  catalog.cattle.io/release-name: elemental-operator-crds
apiVersion: v2
appVersion: 1.6.5
description: A Helm chart for deploying Rancher Elemental Operator CRDs
name: elemental-crd
type: application
version: 104.2.1+up1.6.5
