annotations:
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/hidden: "true"
  catalog.cattle.io/kube-version: < 1.33.0-0
  catalog.cattle.io/managed: "true"
  catalog.cattle.io/namespace: cattle-system
  catalog.cattle.io/os: linux
  catalog.cattle.io/permits-os: linux,windows
  catalog.cattle.io/rancher-version: '>= 2.11.0-0 < 2.12.0-0'
  catalog.cattle.io/release-name: rancher-webhook
apiVersion: v2
appVersion: 0.7.1-rc.3
description: ValidatingAdmissionWebhook for Rancher types
name: rancher-webhook
version: 106.0.1+up0.7.1-rc.3
