annotations:
  catalog.cattle.io/auto-install: rancher-supportability-review-crd=match
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/display-name: Supportability Review
  catalog.cattle.io/kube-version: '>=1.18.0-0 < 1.33.0-0'
  catalog.cattle.io/namespace: sr-operator-system
  catalog.cattle.io/os: linux
  catalog.cattle.io/permits-os: linux
  catalog.cattle.io/provides-gvr: sr.cattle.io.reviewbundles/v1
  catalog.cattle.io/rancher-version: '>= 2.10.0 < 2.11.0'
  catalog.cattle.io/release-name: rancher-supportability-review
  catalog.cattle.io/type: cluster-tool
  catalog.cattle.io/ui-component: rancher-supportability-review
apiVersion: v1
appVersion: 0.1.0
description: The rancher-supportability-review operator enables the functionality
  of Supportability Reviews for Rancher.
icon: https://charts.rancher.io/assets/logos/cis-kube-bench.svg
keywords:
- support
name: rancher-supportability-review
version: 105.0.0+up0.1.0
