annotations:
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/display-name: Prometheus Federator
  catalog.cattle.io/kube-version: '>= 1.27.0-0 < 1.30.0-0'
  catalog.cattle.io/namespace: cattle-monitoring-system
  catalog.cattle.io/os: linux,windows
  catalog.cattle.io/permits-os: linux,windows
  catalog.cattle.io/provides-gvr: helm.cattle.io.projecthelmchart/v1alpha1
  catalog.cattle.io/rancher-version: '>= 2.9.0-0 < 2.10.0-0'
  catalog.cattle.io/release-name: prometheus-federator
apiVersion: v2
appVersion: v0.4.4
dependencies:
- name: helmProjectOperator
  repository: file://./charts/helmProjectOperator
  version: 0.3.2
description: Prometheus Federator
icon: https://raw.githubusercontent.com/rancher/prometheus-federator/main/assets/logos/prometheus-federator.svg
name: prometheus-federator
version: 104.1.0-rc.1+up0.4.5
