apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: reviewbundles.sr.cattle.io
spec:
  group: sr.cattle.io
  names:
    kind: ReviewBundle
    plural: reviewbundles
    singular: reviewbundle
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.timestamp
      name: Timestamp
      type: string
    name: v1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              debug:
                type: boolean
              dev:
                type: boolean
              excludeClusters:
                items:
                  nullable: true
                  type: string
                nullable: true
                type: array
              includeClusters:
                items:
                  nullable: true
                  type: string
                nullable: true
                type: array
              parallelCollection:
                type: boolean
              sonobuoyNamespace:
                nullable: true
                type: string
              sonobuoyTimeout:
                type: integer
              tolerations:
                items:
                  properties:
                    effect:
                      nullable: true
                      type: string
                    key:
                      nullable: true
                      type: string
                    operator:
                      nullable: true
                      type: string
                    tolerationSeconds:
                      nullable: true
                      type: integer
                    value:
                      nullable: true
                      type: string
                  type: object
                nullable: true
                type: array
            type: object
          status:
            properties:
              checkResult:
                nullable: true
                type: string
              clusterCount:
                type: integer
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      nullable: true
                      type: string
                    lastUpdateTime:
                      nullable: true
                      type: string
                    message:
                      nullable: true
                      type: string
                    reason:
                      nullable: true
                      type: string
                    status:
                      nullable: true
                      type: string
                    type:
                      nullable: true
                      type: string
                  type: object
                nullable: true
                type: array
              display:
                nullable: true
                properties:
                  error:
                    type: boolean
                  message:
                    nullable: true
                    type: string
                  state:
                    nullable: true
                    type: string
                  transitioning:
                    type: boolean
                type: object
              fileName:
                nullable: true
                type: string
              fileSize:
                type: integer
              timestamp:
                nullable: true
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
