annotations:
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/hidden: "true"
  catalog.cattle.io/namespace: sr-operator-system
  catalog.cattle.io/release-name: rancher-supportability-review-crd
apiVersion: v1
description: Installs the CRDs for rancher-supportability-review.
name: rancher-supportability-review-crd
type: application
version: 105.0.0+up0.1.0
