annotations:
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/hidden: "true"
  catalog.cattle.io/namespace: longhorn-system
  catalog.cattle.io/release-name: longhorn-crd
apiVersion: v1
appVersion: v1.7.2
description: Installs the CRDs for longhorn.
name: longhorn-crd
type: application
version: 103.4.1+up1.7.2
