annotations:
  catalog.cattle.io/hidden: "true"
  catalog.cattle.io/kube-version: '>= 1.26.0-0 < 1.31.0-0'
  catalog.cattle.io/os: windows
  catalog.rancher.io/certified: rancher
  catalog.rancher.io/namespace: cattle-monitoring-system
  catalog.rancher.io/release-name: rancher-windows-exporter
apiVersion: v2
appVersion: 0.29.2
description: A Helm chart for prometheus windows-exporter
home: https://github.com/prometheus-community/windows_exporter/
keywords:
- windows-exporter
- windows
- prometheus
- exporter
maintainers:
- email: github@jkroepke.de
  name: jkroepke
name: windowsExporter
sources:
- https://github.com/prometheus-community/windows_exporter/
type: application
version: 0.7.1
