name: trigger-test

on:
  workflow_dispatch:
    inputs:
      chart:
        description: "Chart name"
        required: true
        default: "example-chart"
      branch:
        description: "Branch name (only dev branches)"
        required: true
        default: "dev-v2.10"


jobs:
  auto-bump:
    uses: ./.github/workflows/auto-bump.yaml
    with:
      eventPayload: '{"chart": "${{ github.event.inputs.chart }}", "branch": "${{ github.event.inputs.branch }}"}'
